# Generated by Django 5.2.1 on 2025-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='ingredientes',
            field=models.TextField(max_length=255),
        ),
    ]
