# Generated by Django 5.2 on 2025-05-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.FloatField(default=0),
        ),
    ]
