# Generated by Django 5.2.1 on 2025-05-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_pedido_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PREPARANDO', 'Preparando'), ('TERMINADO', 'Terminado')], default='PREPARANDO', max_length=20),
        ),
    ]
