# Generated by Django 5.2 on 2025-05-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('ingredientes', models.TextField(max_length=250)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='Telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
