# Generated by Django 5.1.7 on 2025-05-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_alter_cartao_nombre'),
        ('pizzaapp', '0003_crear_mesas'),
    ]

    operations = [
    ]
