# Generated by Django 5.2 on 2025-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_cartao_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='imagen',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
