# Generated by Django 5.2.1 on 2025-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_camarero',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=20),
        ),
    ]
