# Generated by Django 5.2.1 on 2025-05-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_alter_usuario_apellidos'),
        ('pizzaapp', '0003_pedido_mesa'),
        ('pizzaapp', '0004_pedido_estado_camarero'),
    ]

    operations = [
    ]
