# Generated by Django 5.2.1 on 2025-05-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_alter_pedido_mesa'),
        ('pizzaapp', '0004_merge_0002_alter_cartao_nombre_0003_crear_mesas'),
        ('pizzaapp', '0004_pedido_estado_camarero'),
    ]

    operations = [
    ]
