# Generated by Django 5.2.1 on 2025-05-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_merge_20250523_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_camarero',
        ),
    ]
