# Generated by Django 5.1.7 on 2025-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='disponible',
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('OCUPADO', 'Ocupado'), ('LIBRE', 'Libre'), ('RESERVADO', 'Reservado')], default='LIBRE', max_length=10),
        ),
    ]
