# Generated by Django 5.2.1 on 2025-05-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_merge_20250523_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_camarero',
        ),
    ]
