# Generated by Django 5.2.1 on 2025-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_remove_pedido_estado_remove_pedido_estado_camarero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PREPARANDO', 'Preparando'), ('TERMINADO', 'Terminado')], default='PREPARANDO', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_camarero',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=20),
        ),
    ]
