# Generated by Django 5.2.1 on 2025-05-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_pedido_lineapedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Telefono',
        ),
        migrations.AlterField(
            model_name='cartao',
            name='imagen',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
