# Generated by Django 5.2.1 on 2025-05-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_pedido_lineapedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Telefono',
        ),
    ]
