# Generated by Django 5.2.1 on 2025-05-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_pedido_lineapedido'),
        ('pizzaapp', '0006_remove_mesa_disponible_mesa_estado'),
    ]

    operations = [
    ]
