# Generated by Django 5.2.1 on 2025-05-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0007_merge_20250518_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Telefono',
        ),
    ]
