# Generated by Django 5.2.1 on 2025-05-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_remove_usuario_telefono_usuario_fecha_creacion_and_more'),
        ('pizzaapp', '0007_merge_20250518_2243'),
        ('pizzaapp', '0007_remove_usuario_telefono_alter_cartao_imagen'),
    ]

    operations = [
    ]
