# Generated by Django 5.1.7 on 2025-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0008_remove_usuario_telefono'),
        ('pizzaapp', '0009_crear_mesas'),
    ]

    operations = [
    ]
